version: '3'
services:
  web:
    image: onst  # Используйте ваш образ Django
    container_name: shop
    command: python /OnSt/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/OnSt
    depends_on:
      - db

  db:
    image: postgres:14.9
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pg_data:
