# Generated by Django 4.2.4 on 2023-08-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
