# Generated by Django 4.2.4 on 2023-08-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cart_added_at_cart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
